NIFTY_50_TICKERS = [
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "INFY.NS", "ICICIBANK.NS",
    "HINDUNILVR.NS", "ITC.NS", "SBIN.NS", "BHARTIARTL.NS", "KOTAKBANK.NS",
    "LT.NS", "WIPRO.NS", "AXISBANK.NS", "BAJFINANCE.NS", "MARUTI.NS",
    "SUNPHARMA.NS", "TITAN.NS", "ULTRACEMCO.NS", "NTPC.NS", "POWERGRID.NS",
    "M&M.NS", "ASIANPAINT.NS", "HCLTECH.NS", "NESTLEIND.NS",
    "JSWSTEEL.NS", "TATASTEEL.NS", "ADANIPORTS.NS", "COALINDIA.NS", "GRASIM.NS",
    "BAJAJ-AUTO.NS", "HEROMOTOCO.NS", "EICHERMOT.NS", "HINDALCO.NS", "TECHM.NS",
    "ONGC.NS", "BPCL.NS", "BRITANNIA.NS", "INDUSINDBK.NS", "SBILIFE.NS",
    "BAJAJFINSV.NS", "CIPLA.NS", "DIVISLAB.NS", "DRREDDY.NS", "APOLLOHOSP.NS",
    "ADANIENT.NS", "HDFCLIFE.NS", "BEL.NS", "TRENT.NS",
]

NIFTY_50_INDEX_TICKER = "^NSEI"


def get_nifty_50_symbols():
    return list(NIFTY_50_TICKERS)
